/* Generated by Yosys 0.51 (git sha1 c4b519022, ccache clang 18.1.3 -O3 -flto -flto) */

(* top =  1  *)
(* src = "/Users/roberttaylor/Code/ChipFlow/Amaranth/amaranth/docs/_code/up_counter.py:34" *)
(* generator = "Amaranth" *)
module top(clk, rst, ovf, en);
  reg \$auto$verilog_backend.cc:2355:dump_module$1  = 0;
  wire [16:0] \$1 ;
  reg [15:0] \$2 ;
  (* src = "/Users/roberttaylor/Code/ChipFlow/Amaranth/amaranth/amaranth/hdl/_ir.py:215" *)
  input clk;
  wire clk;
  (* src = "/Users/roberttaylor/Code/ChipFlow/Amaranth/amaranth/docs/_code/up_counter.py:29" *)
  reg [15:0] count = 16'h0000;
  (* src = "/Users/roberttaylor/Code/ChipFlow/Amaranth/amaranth/docs/_code/up_counter.py:24" *)
  input en;
  wire en;
  (* src = "/Users/roberttaylor/Code/ChipFlow/Amaranth/amaranth/docs/_code/up_counter.py:25" *)
  output ovf;
  wire ovf;
  (* src = "/Users/roberttaylor/Code/ChipFlow/Amaranth/amaranth/amaranth/hdl/_ir.py:215" *)
  input rst;
  wire rst;
  assign ovf = count == (* src = "/Users/roberttaylor/Code/ChipFlow/Amaranth/amaranth/docs/_code/up_counter.py:36" *) 5'h19;
  assign \$1  = count + (* src = "/Users/roberttaylor/Code/ChipFlow/Amaranth/amaranth/docs/_code/up_counter.py:42" *) 1'h1;
  (* src = "/Users/roberttaylor/Code/ChipFlow/Amaranth/amaranth/docs/_code/up_counter.py:29" *)
  always @(posedge clk)
    count <= \$2 ;
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$1 ) begin end
    \$2  = count;
    if (en) begin
      (* full_case = 32'd1 *)
      if (ovf) begin
        \$2  = 16'h0000;
      end else begin
        \$2  = \$1 [15:0];
      end
    end
    if (rst) begin
      \$2  = 16'h0000;
    end
  end
endmodule
